name: mbb-cc66v-1-assignment-1
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipywidgets
  - jupyterlab>=4
  - jupyterlab_widgets
  - ipykernel
  - numpy=1.26.*
  - pandas>=2.0
  - matplotlib>=3.8
  - scikit-learn>=1.4
  - pillow>=10.0
  - tqdm>=4.66
  - gensim=4.3.3
  - pytorch=2.3
  - torchvision=0.18
  - pytorch-cuda=12.1
  - fastparquet 
  - pip
  - pip:
      - transformers>=4.47
      - accelerate>=0.33
      - safetensors>=0.4
      - sentencepiece>=0.2
